In [1]:
import torch

In [2]:
def describe(x):
    print("Type: {}".format(x.type()))
    print("Shape/size: {}".format(x.shape))
    print("Values: \n{}".format(x))

In [8]:
describe(torch.Tensor(2, 3))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.0000e+00, 0.0000e+00, 8.4078e-45],
        [0.0000e+00, 1.4013e-45, 0.0000e+00]])


In [9]:
describe(torch.rand(2, 3))   # случайное равномерное распределение(0:1)
describe(torch.randn(2, 3))  # случайное нормальное распределение

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.1451, 0.8547, 0.5852],
        [0.8791, 0.4042, 0.6073]])
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[-0.5862, -1.1645, -0.9653],
        [-0.9370,  0.6998,  0.0158]])
